name: GitHub Actions Demo
run-name: BLS Update
on: 
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:      

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Run BLS script
        run: API Call.py

      - name: Commit and push updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/bls_data.csv
          git commit -m "Monthly BLS data update" || echo "No changes to commit"
          git push
